#!/bin/bash

album_art_url=$(dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:"org.mpris.MediaPlayer2.Player" string:"Metadata" | grep -A 1 "string \"mpris:artUrl\"" | tail -n 1 | cut -d '"' -f 2)

if dbus-send --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Peer.Ping 2>/dev/null; then
  aria2c -q --max-download-limit=20k --auto-file-renaming=false --allow-overwrite=true --dir=script/ -o image.png "$album_art_url"
fi

echo "script/image.png"
