#!/bin/bash

state=$(eww get cal_rev)

open_tray() {
    if [[ -z $(eww list-windows | grep '*calendar') ]]; then
        eww open calendar
    fi
    eww update cal_rev=true
}

close_tray() {
    eww update cal_rev=false
}

case $1 in
    close)
        close_tray
        exit 0 ;;
esac

case $state in
    true)
        close_tray ;;
    false)
        open_tray ;;
esac
