#!/bin/bash

state=$(eww get update_rev)

open_tray() {
    if [[ -z $(eww list-windows | grep '*window-package') ]]; then
        eww open window-package
    fi
    eww update update_rev=true
}

close_tray() {
    eww update update_rev=false
}

case $1 in
    close)
        close_tray
        exit 0 ;;
esac

case $state in
    true)
        close_tray ;;
    false)
        open_tray ;;
esac
