#!/bin/bash

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

NAMA=${USER}
WAKTU=$(date +%c)
JAM=$(date +%k)

clock_boot() {
    if [[ 5 -ge "$JAM" && "$JAM" -le 12 ]]; then
        mpg123 ~/.config/hypr/scripts/audiofile/xp_sound.mp3
        sleep 8
        notify-send -a "arch@gilang" "Hai Gilang, selamat pagi" "$WAKTU" -i /home/gilang/.local/share/icons/Papirus/48x48/apps/org.kde.archUpdate.svg
    elif [[ 12 -ge "$JAM" && "$JAM" -le 16 ]]; then
        mpg123 ~/.config/hypr/scripts/audiofile/xp_sound.mp3
        sleep 8
        notify-send -a "arch@gilang" "Hai Gilang, selamat siang" "$WAKTU" -i /home/gilang/.local/share/icons/Papirus/48x48/apps/org.kde.archUpdate.svg
    elif [[ 16 -ge "$JAM" && "$JAM" -le 19 ]]; then
        mpg123 ~/.config/hypr/scripts/audiofile/xp_sound.mp3
        sleep 8
        notify-send -a "arch@gilang" "Hai Gilang, selamat sore" "$WAKTU" -i /home/gilang/.local/share/icons/Papirus/48x48/apps/org.kde.archUpdate.svg
    else
        mpg123 ~/.config/hypr/scripts/audiofile/xp_sound.mp3
        sleep 8
        notify-send -a "arch@gilang" "Hai Gilang, selamat malam" "$WAKTU" -i /home/gilang/.local/share/icons/Papirus/48x48/apps/org.kde.archUpdate.svg
    fi
}

query_wall() {
    sleep 1
    QUERY_EDP=$(cat ~/.cache/wall)
    FILE_EDP=$(echo "$QUERY_EDP" | grep "eDP-1" | grep -oP '(?<=image: ).*\.png')
    OUTPUT_EDP=$(echo "$FILE_EDP")

    QUERY_HDMI=$(cat ~/.cache/wall)
    FILE_HDMI=$(echo "$QUERY_HDMI" | grep "HDMI-A-2" | grep -oP '(?<=image: ).*\.png')
    OUTPUT_HDMI=$(echo "$FILE_HDMI")

    swww query|| swww-daemon -f xrgb

    swww img $OUTPUT_EDP --outputs "eDP-1" --transition-bezier 1,.01,0,1.05 --transition-duration 2.1 --transition-type grow  --transition-step 255 --transition-pos top-right --transition-fps 60

    swww img $OUTPUT_HDMI --outputs "HDMI-A-2" --transition-bezier 1,.01,0,1.05 --transition-duration 2.1 --transition-type grow  --transition-step 255 --transition-pos top-right --transition-fps 60
}

query_wall &
clock_boot
